sudo: required
services:
  - docker
language: generic
before_install:
  - docker build -e CI=true -t adamj335/docker-training -f Dockerfile.dev .


script:
  - docker run adamj335/docker-training npm run test -- --coverage
